# Generated by Django 5.1 on 2024-08-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_inflow_unit_item_outflow_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='outflow_frequency',
            field=models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('irregular', 'Irregular')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_frequency',
            field=models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('irregular', 'Irregular')], max_length=50),
        ),
    ]
