# Generated by Django 5.1 on 2024-08-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_item_outflow_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sector',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sector_item', to='stock.sector'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='sector_item', to='stock.unit'),
            preserve_default=False,
        ),
    ]
