# Generated by Django 5.1 on 2024-08-31 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_item_sector_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
    ]
