# Generated by Django 5.1 on 2024-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sector',
        ),
        migrations.AddField(
            model_name='item',
            name='sector',
            field=models.ManyToManyField(related_name='sector_item', to='stock.sector'),
        ),
    ]
