# Generated by Django 5.1 on 2024-09-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_remove_item_sector_item_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
