# Generated by Django 5.1 on 2024-09-01 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflow',
            name='source_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inflow_source', to='stock.unit'),
        ),
    ]
