# Generated by Django 5.1 on 2024-09-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_inflow_source_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Análise', 'Análise'), ('Negado', 'Negado')], default='Análise', max_length=20),
        ),
    ]
