# Generated by Django 5.1 on 2024-09-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_request_user_alter_request_approval_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceorder',
            old_name='deleviry_date',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='serviceorder',
            old_name='deleviry_forecast',
            new_name='delivery_forecast',
        ),
    ]
