# Generated by Django 5.1 on 2024-09-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_serviceorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='delivery_status',
            field=models.CharField(choices=[('Efetuada', 'Efetuada'), ('Não efetuada', 'Não efetuada')], default='Não efetuada', max_length=20),
        ),
    ]
