# Generated by Django 5.1 on 2024-10-08 11:29

import django.db.models.deletion
from django.db import migrations, models

def migrate_supplier_to_suppliers(apps, schema_editor):
    Item = apps.get_model('stock', 'Item')
    for item in Item.objects.all():
        if item.supplier:
            item.suppliers.add(item.supplier)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_request_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='suppliers',
            field=models.ManyToManyField(related_name='suppliers_item', to='stock.supplier'),
        ),
    ]
