# Generated by Django 5.1 on 2024-10-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_inflow_supplier_item_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
    ]
