# Generated by Django 5.1 on 2024-10-21 15:37
from django.db import migrations, models

def migrate_nomenclaturas(apps, schema_editor):
    # Obtendo os modelos Item e Nomenclatura
    Item = apps.get_model('stock', 'Item')
    Nomenclature = apps.get_model('stock', 'Nomenclature')

    # Iterar sobre todos os itens e criar nomenclaturas
    for item in Item.objects.all():
        Nomenclature.objects.create(name=item.nomenclature)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0017_alter_supplier_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunPython(migrate_nomenclaturas),
    ]