# Generated by Django 5.1 on 2024-10-21 16:47

from django.db import migrations, models

def migrate_nomenclaturas(apps, schema_editor):
    # Obtendo os modelos Item e Nomenclatura
    Item = apps.get_model('stock', 'Item')
    Nomenclature = apps.get_model('stock', 'Nomenclature')
    # Iterar sobre todos os itens e criar nomenclatures
    for item in Item.objects.all():
        nomenclature = Nomenclature.objects.get(name=item.nomenclature)
        item.nomenclatures.add(nomenclature)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_nomenclature'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='nomenclatures',
            field=models.ManyToManyField(related_name='nomenclatures_item', to='stock.nomenclature'),
        ),
        migrations.RunPython(migrate_nomenclaturas),
    ]
