# Generated by Django 5.1 on 2024-10-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_item_nomenclatures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='nomenclature',
        ),
    ]
