# Generated by Django 5.1 on 2024-10-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_remove_item_nomenclature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomenclature',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
