# Generated by Django 5.1 on 2024-10-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0022_supplier_cpf_alter_supplier_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='corporate_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='seller',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
