# Generated by Django 5.1 on 2024-10-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_supplier_corporate_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='outflow',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outflow_inflwo', to='stock.outflow'),
        ),
    ]
