# Generated by Django 5.1 on 2024-10-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_inflow_outflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitem',
            name='approve_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
