# Generated by Django 5.1 on 2024-09-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinflow',
            name='status',
            field=models.CharField(choices=[('efetuado', 'Efetuado'), ('não efetuado', 'Não Efetuado')], default='Não Efetuado', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='payment_method',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('cartão de crédito', 'Cartão de Crédito'), ('cartão de Dédito', 'Cartão de Dédito'), ('boleto', 'Boleto'), ('pix', 'Pix'), ('ted', 'TED'), ('doc', 'DOC'), ('cheque', 'Cheque')], max_length=45),
        ),
    ]
