# Generated by Django 5.1 on 2024-09-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_cashoutflow_status_alter_cashoutflow_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='recive_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
