# Generated by Django 5.1 on 2024-09-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_cashoutflow_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('view_cashflow', 'Can view cash flow')],
            },
        ),
    ]
