# Generated by Django 5.1 on 2024-09-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_financialcategory_financialclasification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='financialcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='financialclasification',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='revenuecenter',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='cashinflow',
            name='financial_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='financial_category', to='financial.financialcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashinflow',
            name='financial_classification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='financial_classification', to='financial.financialclasification'),
            preserve_default=False,
        ),
    ]
