# Generated by Django 5.1 on 2024-09-11 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_alter_client_options_alter_costcenter_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutflow',
            name='financial_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='financial_category_outflow', to='financial.financialcategory'),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='financial_classification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='financial_classification_outflow', to='financial.financialclasification'),
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='financial_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_category_inflow', to='financial.financialcategory'),
        ),
        migrations.AlterField(
            model_name='cashinflow',
            name='financial_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_classification_inflow', to='financial.financialclasification'),
        ),
    ]
