# Generated by Django 5.1 on 2024-09-17 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_alter_cashinflow_financial_category_and_more'),
        ('stock', '0013_request_delivery_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={},
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='name',
        ),
        migrations.AddField(
            model_name='costcenter',
            name='id_center',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='sector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.sector'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='fine',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costcenter', to='financial.area'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='final_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costcenter_final', to='financial.area'),
        ),
    ]
