# Generated by Django 5.1 on 2024-09-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_finalarea_alter_costcenter_final_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='final_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costcenter_final', to='financial.area'),
        ),
        migrations.DeleteModel(
            name='FinalArea',
        ),
    ]
