# Generated by Django 5.1 on 2024-09-17 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0019_alter_costcenter_options_alter_revenuecenter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuecenter',
            name='final_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_area_revenue', to='financial.area'),
        ),
    ]
