# Generated by Django 5.1 on 2024-09-18 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_alter_revenuecenter_final_area'),
        ('stock', '0013_request_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuecenter',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenuecenter', to='financial.area'),
        ),
        migrations.AlterField(
            model_name='revenuecenter',
            name='final_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenuecenter_final', to='financial.area'),
        ),
        migrations.AlterField(
            model_name='revenuecenter',
            name='id_center',
            field=models.CharField(blank=True, default=3, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revenuecenter',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.sector'),
        ),
    ]
