# Generated by Django 5.1 on 2024-09-21 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_alter_revenuecenter_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plan', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_accounts', to='financial.financialclasification')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classification_accounts', to='financial.financialclasification')),
            ],
        ),
    ]
