# Generated by Django 5.1 on 2024-09-23 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_remove_cashinflow_financial_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_accounts', to='financial.financialcategory'),
        ),
    ]
