# Generated by Django 5.1 on 2024-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_alter_chartofaccounts_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_id', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('tpe', models.CharField(choices=[('Corrente', 'Corrente'), ('Investimento', 'Investimento'), ('Poupança', 'Poupança'), ('Caixa Pequeno', 'Caixa Pequeno')], max_length=100)),
                ('value', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['bank'],
            },
        ),
    ]
