# Generated by Django 5.1 on 2024-09-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinflow',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount'),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.bankaccount'),
        ),
    ]
