# Generated by Django 5.1 on 2024-10-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_cashinflow_bank_account_cashoutflow_bank_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('description', models.TextField(max_length=200)),
                ('bank_code', models.CharField(max_length=20)),
                ('branch', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('efetuado', 'Efetuado'), ('não efetuado', 'Não Efetuado')], default='não efetuada', max_length=50)),
            ],
            options={
                'ordering': ['date', 'value'],
            },
        ),
    ]
