# Generated by Django 5.1 on 2024-10-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0027_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinflow',
            name='fees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashinflow',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
