# Generated by Django 5.1 on 2024-10-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_cashinflow_fees_cashinflow_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutflow',
            name='fees',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
