# Generated by Django 5.1 on 2024-10-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_cashoutflow_fees_cashoutflow_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartofaccounts',
            options={'ordering': ['id_plan']},
        ),
    ]
