# Generated by Django 5.1 on 2024-10-11 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_rename_financialclasification_subcategory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='FinancialSubcategory',
        ),
    ]
