# Generated by Django 5.1 on 2024-10-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0033_rename_financialcategory_financialaccounting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
