# Generated by Django 5.1 on 2024-10-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0034_financialcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccounts',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_accounts', to='financial.financialcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='accounting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_accounts', to='financial.financialaccounting'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_accounts', to='financial.financialsubcategory'),
        ),
    ]
