# Generated by Django 5.1 on 2024-10-11 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_chartofaccounts_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccounts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_accounts', to='financial.financialcategory'),
        ),
        migrations.AlterField(
            model_name='chartofaccounts',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_accounts', to='financial.financialsubcategory'),
        ),
    ]
