# Generated by Django 5.1 on 2024-10-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0037_alter_financialaccounting_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccounting',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='financialsubcategory',
            options={'ordering': ['name']},
        ),
    ]
