# Generated by Django 5.1 on 2024-10-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_alter_financialaccounting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashinflow',
            name='status',
            field=models.CharField(choices=[('Efetuado', 'Efetuado'), ('não efetuado', 'Não Efetuado')], default='Não Efetuado', max_length=50),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='status',
            field=models.CharField(choices=[('Efetuado', 'Efetuado'), ('não efetuado', 'Não Efetuado')], default='Não Efetuado', max_length=50),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('Efetuado', 'Efetuado'), ('não efetuado', 'Não Efetuado')], default='não efetuada', max_length=50),
        ),
    ]
