# Generated by Django 5.1 on 2024-10-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0039_alter_cashinflow_status_alter_cashoutflow_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('xml_file', models.FileField(upload_to='nfe_xmls/')),
                ('total_value', models.FloatField(blank=True, null=True)),
                ('issue_date', models.DateField()),
            ],
            options={
                'ordering': ['issue_date'],
            },
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
