# Generated by Django 5.1 on 2024-10-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0040_invoice_alter_cashoutflow_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_cente_cashoutflow', to='financial.costcenter'),
        ),
    ]
