# Generated by Django 5.1 on 2024-10-23 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0041_alter_cashoutflow_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='chart_of_accounts',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chart_cash_outflow', to='financial.chartofaccounts'),
        ),
    ]
