# Generated by Django 5.1 on 2024-10-29 12:21

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0043_alter_cashoutflow_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='cnpj',
            field=localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, unique=True),
        ),
    ]
