# Generated by Django 5.1 on 2024-08-31 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_image/')),
                ('position', models.CharField(choices=[('Estagiário', 'Estagiário'), ('Auxiliar', 'Auxiliar'), ('Assistente', 'Assistente'), ('Gerente', 'Gerente'), ('Diretor', 'Diretor')], max_length=50)),
                ('sector', models.ManyToManyField(related_name='user_sector', to='stock.sector')),
                ('unit', models.ManyToManyField(related_name='user_unit', to='stock.unit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
